config/routes.rb
Rails.application.routes.draw do

  resources :photos, only: [:new, :create, :index, :show]
  root to: 'photos#index'
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  dragonfly_accessor :image do
    after_assign do |img|
      img.encode!('jpg', '-quality 80') if img.image?
     end
  end

  validates :title, presence: true, length: {minimum: 2, maximum: 20}
  validates :image, presence: true

  validates :image, presence: true
  validates_size_of :image, maximum: 500.kilobytes,
                    message: "should be no more than 500 KB", if: :image_changed?

  validates_property :format, of: :image, in: [:jpeg, :jpg, :png, :bmp], case_sensitive: false,
                     message: "should be either .jpeg, .jpg, .png, .bmp", if: :image_changed?
end

app/models/thumb.rb
class Thumb < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.all
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      flash[:success] = "Photo saved!"
      redirect_to photos_path
    else
      render 'new'
    end
  end

  def show
    @photo = Photo.find(params[:id])
  end

  private

  def photo_params
    params.require(:photo).permit(:image, :title, :image_size)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DragonflyPg</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/index.html.erb
<h1>List of photos</h1>

<%= link_to 'Add your photo', new_photo_path, class: 'btn btn-lg btn-primary' %>

<ul class="row" id="photos-list">
  <% @photos.each do |photo| %>
    <li class="col-xs-3">
      <%= link_to image_tag(photo.image.thumb('180x180#').url, alt: photo.title, class: 'img-thumbnail'), photo.image.remote_url, target: '_blank' %>
      <%= link_to image_tag(photo.image.url, alt: photo.title, class: 'img-thumbnail'), photo.image.remote_url, target: '_blank' %>
      <p><%= photo.title %></p>
      <small><%= number_to_human_size photo.image.size %></small>
    </li>
  <% end %>
</ul>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= form_for @photo do |f| %>
  <%= render 'shared/errors', object: @photo %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, required: true %>
  </div>

  <div class="form-group">
    <%= f.label :image_size %>
    <%= f.text_field :image_size, class: 'form-control', required: false %>
  </div>

  <%= f.submit 'Submit', class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/photos/show.html.erb
<%= link_to image_tag(@photo.image.thumb('180x180#').url, alt: @photo.title, class: 'img-thumbnail'), @photo.image.remote_url, target: '_blank' %>
  <p><%= @photo.title %></p>
  <small><%= number_to_human_size @photo.image.size %></small>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="errors_full_text" class="bg-warning">
    <h2>Found these errors when saving:</h2>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>